spring:
  application.name: Task3
  profiles.active: local
  jackson:
    date-format: "dd-MM-yyyy"
    serialization:
      write_dates_as_timestamps: false

  datasource:
    url: "jdbc:postgresql://localhost:5432/UnauthorizedDeliveries"
    username: "postgres"
    password: "123456789"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
  servlet.context-path: /base